### ISSUE TITLE
How to evaluate the radio 802.11ah

### ISSUE THREAD

**Issue by edgaralb** [newracom/nrc7292_sw_pkg#11]
Please, what tool, application or how can I evaluate the transmission and reception only of the physical layer (RF), without using the MAC layer.

**Comment by newracom** [comment]
Dear Edgar,

Sorry for the late reply.
We have an application to evaluate the transmission and reception of the physical layer (RF) without the MAC layer. However, it is only disclosed to companies that have signed an NDA. If you have more questions, please send an email to db.kim@newracom.com.

Best regards,
Newracom
