### ISSUE TITLE
Fix kernel_read prototype on Linux kernel 4.9

### ISSUE THREAD

**Issue by kevlo** [newracom/nrc7292_sw_pkg#12]
The diff below fixes kernel_read prototype on Linux kernel 4.9.

[kernel_read.txt](https://github.com/newracom/nrc7292_sw_pkg/files/6820115/kernel_read.txt)

**Comment by newracom** [comment]
Dear Kevin,

Thank you for your contribution.
We confirmed your patch and it will be applied to the next release.

Best regards,
Newracom
