### ISSUE TITLE
Does the driver support wireless ad-hoc mode?

### ISSUE THREAD

**Issue by chiuyinglay** [newracom/nrc7292_sw_pkg#32]
I was trying to setup 2 HaLow Board in ad-hoc mode. However, I encountered error as below:

sudo iwconfig wlan0 mode ad-hoc
Error for wireless request "Set Mode" (8B06) :
    SET failed on device wlan0 ; Operation not supported.

**Comment by newracom** [comment]
Dear @chiuyinglay,

Thank you for your inquiry.
NRC7292 doesn't support ad-hoc mode at the moment, but we support IEEE 802.11s mesh network.
Please refer to https://github.com/newracom/nrc7292_sw_pkg/blob/master/package/host/doc/AN-7292-007-11s_mesh_network.pdf.

Best regards,
Newracom

**Comment by chiuyinglay** [comment]
Thanks. Will there be any chance of supporting ad-hoc mode in the future?
