### ISSUE TITLE
Duty Cycle EU

### ISSUE THREAD

**Issue by GerritKuehnle** [newracom/nrc7292_sw_pkg#46]
Is there a way to set/change a duty cycle with EU settings?
The only setting i could find was in the CLI-App, but the set and show commands are only available with JP settings.

**Comment by newracom** [comment]
Dear @GerritKuehnle,

The duty cycle setting command of cli_app can be applied to EU settings.
But we verified duty cycle setting only for JP because recent EU regulation update is not finalized yet.

Best regards,
Newracom

**Comment by newracom** [comment]
Dear @GerritKuehnle,

If you have no further question, I'd like to close this issue.

Best regards,
Newracom
