### ISSUE TITLE
Unknown symbol in module when insmod nrc.ko

### ISSUE THREAD

**Issue by tomcattw** [newracom/nrc7292_sw_pkg#52]
I follow the whole procedure, then run 
 ./start.py 1 0 EU
in Loading module step, error occured as following 

sudo insmod /home/pi/nrc_pkg/sw/driver/nrc.ko  hifspeed=20000000 spi_bus_num=0 spi_cs_num=0 spi_gpio_irq=5 spi_polling_interval=0 fw_name=uni_s1g.bin bss_max_idle=180 ndp_preq=1 auto_ba=1 listen_interval=1000
insmod: ERROR: could not insert module /home/pi/nrc_pkg/sw/driver/nrc.ko: Unknown symbol in module
I install module manually, the same erro ... 
![image](https://user-images.githubusercontent.com/26920231/193440972-ad97596d-c255-4b8c-9cce-68e2a73e7bab.png)

How to solve " Unknown symbol in module"
Thanks.

**Comment by enganguish** [comment]
How did you create nrc.ko? Was it built on you RPi?

If the kernel version of your RPi is not 4.14.70, you should build it again based on your environment.
the nrc.ko in nrc7292_sw_pkg has been created for 4.14.70 by default.

**Comment by tumist** [comment]
Make sure the kernel module mac80211 is loaded

**Comment by newracom** [comment]
I'd like to close this issue. Please open a new one if there's any further issue.
