### ISSUE TITLE
One of the guides generated with broken references

### ISSUE THREAD

**Issue by Ankush-Pathak** [newracom/nrc7292_sw_pkg#56]
This [guide](https://github.com/newracom/nrc7292_sw_pkg/blob/master/package/host/doc/AN-7292-007-11s_mesh_network.pdf) has a lot of broken references, indicated by `Error! Reference source not found.` in the PDF.

**Comment by newracom** [comment]
Dear @Ankush-Pathak,

Thank you for your report.
We fixed broken references, and the updated guide will be included in the upcoming release.
FYI, I attached the fixed one: [AN-7292-007-11s_mesh_network.pdf](https://github.com/newracom/nrc7292_sw_pkg/files/9974009/AN-7292-007-11s_mesh_network.pdf)

Best regards,
Newracom
