### ISSUE TITLE
Where is the firmware nrc7292_cspi.bin source codes?

### ISSUE THREAD

**Issue by webrtcccccc** [newracom/nrc7292_sw_pkg#57]
Dear Sir, 

How can I build "package/host/evk/binary/nrc7292_cspi.bin" myself?
I can not find firmware nrc7292_cspi.bin source code in the project.

Please help thanks~

**Comment by newracom** [comment]
Dear @webrtcccccc,

We don't provide source code of firmware.

Best regards,
Newracom
