### ISSUE TITLE
MAC Frame preamble period

### ISSUE THREAD

**Issue by webrtcccccc** [newracom/nrc7292_sw_pkg#64]
Dear Sir,

Is there any option to set the WiFi MAC Frame preamble period?
I searched the cli_app CMD and start.py, but I could not find any option to set the 'preamble period.'

**Comment by newracom** [comment]
Dear @webrtcccccc,

Unfortunately, we don't provide that option to set the preamble period.

Best regards,
Newracom

**Comment by webrtcccccc** [comment]
I got it. Thank you.
