### ISSUE TITLE
How to use Frequency band 950MHz

### ISSUE THREAD

**Issue by webrtcccccc** [newracom/nrc7292_sw_pkg#68]
Dear nrc Sir,

The Specification mentions that the Frequency band can be 750 to 950MHz.
In the file ap_halow_wpa2.conf, it could not find the 950MHz setting.
How to set to use 950MHz?
https://github.com/newracom/nrc7292_sw_pkg/blob/master/package/host/evk/sw_pkg/nrc_pkg/script/conf/US/ap_halow_wpa2.conf

Thanks.

**Comment by newracom** [comment]
Dear @webrtcccccc,

Irrespective of the supported frequency band, it is essential to comply with the regulations of each regulatory domain. 
It's important to note that there are no 950MHz channel available in the United States.
Please refer to https://github.com/newracom/nrc7292_sw_pkg/blob/master/package/host/doc/UG-7292-003-S1G_Channel.pdf.

Best regards,
Newracom
