### ISSUE TITLE
Running R-pi(4) boradcom WIFI and Halow same time

### ISSUE THREAD

**Issue by J-qb** [newracom/nrc7292_sw_pkg#70]
Hi,
Looking for some help to get the R-pi runing with two interfaces one time - onboard WIFI and Halow?
To what i found:
- on R-pi 3 it works with that imaige: - and it suppose to work like that
https://docs.alfa.com.tw/Product/AHPI7292S/20_Getting_Started/
- for R-pi 4 there is other image availagle
https://docs.alfa.com.tw/Product/AHPI7292S/20_Getting_Started_New/
and in that one cant get broadcom wifi working 

Exactly would like to get it running (wifi + halow) at R-pi Zero w. 
any tips would be welcame.

**Comment by teledatics** [comment]
We have a docs site that shows how to set this up on an RPi:

https://teledatics.com/docs

It documents how to do this on our TD-XPAH EVK hardware, but should be applicable to the Alfa hardware as well.
