### ISSUE TITLE
SIOCSIFFLAGS: Operation not permitted

### ISSUE THREAD

**Issue by AikateriniKyriakou** [newracom/nrc7292_sw_pkg#71]
I have followed the instructions for setup and I have a problem when trying to run start.py script both in AP and in STA mode. The problem is presented in the following log:
_sudo insmod /home/pi/nrc_pkg/sw/driver/nrc.ko  hifspeed=20000000 spi_bus_num=0 spi_cs_num=0 spi_gpio_irq=5 spi_polling_interval=0 fw_name=uni_s1g.bin auto_ba=1 listen_interval=1000
**SIOCSIFFLAGS: Operation not permitted**_

Current dmesg log is:
_[   92.465593] nrc80211 nrc80211: [spi_suspend] drv_state:-1 wowlan_enabled:0 power_save:0
[   92.465607] start FW 336
[   92.901870] end FW
[   95.918923] nrc80211 nrc80211: size of bd file is 2128
[   95.919008] nrc80211 nrc80211: Major 01 Minor 04 Total len 0840 Num_Data_Groups 0009 Checksum 38AB
[   95.919017] nrc80211 nrc80211: target version is not matched(1 : 0)_

HW & SW:  
Halow board: AHPI7292S REV 0C 2021-01-22 
Raspberry PI 3 
OS: Linux raspberrypi 5.10.92-v7+ #1514 SMP Mon Jan 17 17:36:39 GMT 2022 armv7l GNU/Linux
nrc7292_sw_pkg release: v1.3.4_rev14

I tried to update the bd.dat file from these issues: https://github.com/newracom/nrc7292_sw_pkg/issues/60 & https://github.com/newracom/nrc7292_sw_pkg/issues/66 , but it does not seem to work. 

Thanks in advance

**Comment by newracom** [comment]
Dear @AikateriniKyriakou,

Please check these two.
(1) Did you rebuild your host device driver? The nrc.ko binary of the package is for kernel 4.14.70 as mentioned in https://github.com/newracom/nrc7292_sw_pkg/blob/master/release_note/RN-7292-001-SW_PKG_release_note%20(v1.3.4_rev14).pdf.
(2) Did you try with the db.dat file of #60? As you can see at #60, dmesg result showed the same target version mismatch log as yours.

Best regards,
Newracom
