### ISSUE TITLE
Typo in nrc-mac80211 CONFIF_S1G_CHANNEL instead of CONFIG_S1G_CHANNEL

### ISSUE THREAD

**Issue by joenpera** [newracom/nrc7292_sw_pkg#81]
Hi, 

I noticed that the master branch and V1.5 includes a typo in nrc-mac80211.c - source file.

https://github.com/newracom/nrc7292_sw_pkg/blob/1dd6dfb3fb3b552bbc9b47529d60123a141ba0cb/package/src/nrc/nrc-mac80211.c#L185

**CONFIF**_S1G_CHANNEL instead of **CONFIG**_S1G_CHANNEL

**Comment by newracom** [comment]
Dear @joenpera,

Thank you for your report. We will fix this typo soon.

Best regards,
Newracom
