### ISSUE TITLE
test cont_tx not working

### ISSUE THREAD

**Issue by wizath** [newracom/nrc7292_sw_pkg#85]
I'm trying to enable continous tx for testing purposes, Used command according to documentation:

![image](https://github.com/newracom/nrc7292_sw_pkg/assets/11598020/2ff7c645-0734-4eb9-add7-0ab4391b9baf)

Using driver v1.5 from main branch, along with firmware files

But all I got is fail response:
```
./cli_app test cont_tx 9025 1m 7 17 
FAIL
```

Any ideas?

**Comment by newracom** [comment]
Dear @wizath,

The frequency parameter in the sample command is incorrect; it should be in MHz. 
Therefore, 902.5 should be used instead of 9025. My apologies for the confusion. Please use 902.5.

Best,
Newracom

**Comment by wizath** [comment]
Thanks for info
