### ISSUE TITLE
Board Data File

### ISSUE THREAD

**Issue by magicone2571** [newracom/nrc7292_sw_pkg#95]
I have the alfa board like a lot of people. I got everything working on one of them but when I tried a seoncd one, the board file failed. Only difference I can see is the one that works is 7292 0102 1814 for version. And all the other boards I have are 7291 0101 1814. I've tried a bunch of different files from here. Any suggestions? Thanks

**Comment by jr1221** [comment]
How did you fix this?  I seem to have the same issue.

**Comment by magicone2571** [comment]
Lots and lots of luck. It took me nearly 40 hours to get two chips to mesh. There's a .dat file floating around here that might work.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
